import localFont from "next/font/local";
import {Audiowide} from "next/font/google"
import "./globals.css";

const ainohead = localFont({
    src: "./fonts/Aino-Headline.woff2",
    weight: "400",
  });
const aino = localFont({
  src: "./fonts/Aino-Regular.woff2",
  weight: "400",
});
const audiowide = Audiowide({
  weight: "400",
  subsets: ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${aino} ${audiowide} ${ainohead} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
